# Generated by Django 5.1.1 on 2024-10-06 09:52

import cmspage.mixins
import cmspage.models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_title', models.BooleanField(default=True, help_text='Display the page title on the page')),
                ('display_tags', models.BooleanField(default=False, help_text='Display the page tags on the page')),
                ('seo_keywords', models.CharField(blank=True, help_text='SEO Keywords', max_length=255)),
                ('body', wagtail.fields.StreamField([('hero', 4), ('title', 6), ('cards', 17), ('image_and_text', 25), ('cta', 28), ('richtext', 31), ('video', 33), ('large_image', 34), ('table', 35), ('carousel', 36), ('new_section', 37)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bg-transparent', 'Transparent'), ('bg-body', 'Page'), ('bg-light', 'Light'), ('bg-dark', 'Dark'), ('bg-white', 'White'), ('bg-black', 'Dark'), ('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-success', 'Success'), ('bg-warning', 'Warning'), ('bg-info', 'Info'), ('bg-danger', 'Danger')], 'help_text': 'Background type or color'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bg-opacity-100', '100%'), ('bg-opacity-75', '75%'), ('bg-opacity-50', '50%'), ('bg-opacity-25', '25%'), ('bg-gradient', 'Gradient')], 'help_text': 'Background opacity'}), 2: ('wagtail.blocks.StructBlock', [[('background', 0), ('opacity', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('bg', 2), ('image', 3)]], {'label': 'Hero Image', 'max_num': 1}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title text to display', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('bg', 2), ('text', 5)]], {'label': 'Title', 'max_num': 1}), 7: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Bold title text for this card (len=255)', 'label': 'Card Title', 'max_length': 255, 'null': True, 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'help_text': 'Optional text for this card', 'label': 'Card Text', 'null': True, 'required': False}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image (resized)', 'label': 'Card Image', 'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page link', 'required': False}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document link', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Extra link', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Button Title (use hyphen for special link button)', 'max_length': 255, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page_link', 10), ('doc_link', 11), ('extra_link', 12), ('button_title', 13)]], {'help_text': 'Enter a page or document, or an external link', 'label': 'Card Link', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('image', 9), ('link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('bg', 2), ('cards', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'null': True}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width centered'), ('left', 'Image to the left'), ('right', 'Image to the right')], 'help_text': 'Full image - text below, Image left - text right, or image right - text left.'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('standard', 'Standard 786x552'), ('landscape', 'Landscape 786x1104'), ('portrait', 'Portrait 786x300')], 'help_text': 'Layout - match with picture dimensions'}), 21: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Max length of 60 characters.', 'max_length': 60, 'null': True, 'required': False}), 22: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'usefont'], 'help_text': 'Description for this item', 'required': False}), 23: ('wagtail.blocks.BooleanBlock', (), {'blank': True, 'default': False, 'help_text': 'Overlay text on image', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('page_link', 10), ('doc_link', 11), ('extra_link', 12), ('button_title', 13)]], {'blank': True, 'null': True, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('bg', 2), ('image', 18), ('image_alignment', 19), ('image_size', 20), ('title', 21), ('text', 22), ('overlay', 23), ('link', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Max length of 60 characters, optional', 'max_length': 60, 'null': True, 'required': False}), 27: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'usefont'], 'help_text': 'Call to action text, optional (max=200)', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('bg', 2), ('title', 26), ('text', 27), ('link', 24)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Display title, optional (max len=120)', 'max_length': 120, 'null': True, 'required': False}), 30: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'usefont'], 'help_text': 'Rich text block, required'}), 31: ('wagtail.blocks.StructBlock', [[('bg', 2), ('title', 29), ('content', 30)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 33: ('wagtail.blocks.StructBlock', [[('bg', 2), ('title', 26), ('video', 32), ('text', 27)]], {}), 34: ('wagtail.blocks.StructBlock', [[('bg', 2), ('image', 3)]], {}), 35: ('cmspage.blocks.CustomTableBlock', (), {}), 36: ('wagtail.blocks.StructBlock', [[('bg', 2)]], {}), 37: ('cmspage.blocks.NewSectionBlock', (), {})}, null=True)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
            },
            bases=('wagtailcore.page', cmspage.mixins.CMSTemplateMixin),
        ),
        migrations.CreateModel(
            name='CMSPageImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailimages.image',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('carousel_title', models.CharField(blank=True, help_text='Display title, optional (max len=120)', max_length=120, null=True)),
                ('carousel_content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('carousel_attribution', models.CharField(blank=True, help_text='Display title, optional (max len=120)', max_length=120, null=True)),
                ('carousel_interval', models.IntegerField(default=12000, help_text='Keep visible for time in milliseconds')),
                ('carousel_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('parent_pg', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='cmspage.cmspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_order', models.IntegerField(default=0, help_text='Specify the order in the menu', verbose_name='Order')),
                ('menu_title', models.CharField(blank=True, help_text='Override the menu title', max_length=32, null=True, validators=[cmspage.models.min_length_validator], verbose_name='Menu Title')),
                ('link_url', models.URLField(blank=True, help_text='Set a custom URL if not linking to a page or document.Title is required for this link type', verbose_name='External Link')),
                ('menu_icon', models.CharField(blank=True, choices=[('', 'No Icon'), ('cmspage/icons/cards/ace-of-clubs.svg', 'Ace Of Clubs'), ('cmspage/icons/cards/ace-of-diamonds.svg', 'Ace Of Diamonds'), ('cmspage/icons/cards/ace-of-hearts.svg', 'Ace Of Hearts'), ('cmspage/icons/cards/ace-of-spades.svg', 'Ace Of Spades'), ('cmspage/icons/living/airplane.svg', 'Airplane'), ('cmspage/icons/symbols/anchor.svg', 'Anchor'), ('cmspage/icons/symbols/apply.svg', 'Apply'), ('cmspage/icons/symbols/arrow-down.svg', 'Arrow Down'), ('cmspage/icons/symbols/arrow-end.svg', 'Arrow End'), ('cmspage/icons/symbols/arrow-left.svg', 'Arrow Left'), ('cmspage/icons/symbols/arrow-right.svg', 'Arrow Right'), ('cmspage/icons/symbols/arrow-start.svg', 'Arrow Start'), ('cmspage/icons/symbols/arrow-up.svg', 'Arrow Up'), ('cmspage/icons/people/baby.svg', 'Baby'), ('cmspage/icons/living/bloom.svg', 'Bloom'), ('cmspage/icons/living/book-open.svg', 'Book Open'), ('cmspage/icons/people/brain.svg', 'Brain'), ('cmspage/icons/symbols/broadcast.svg', 'Broadcast'), ('cmspage/icons/living/car-side.svg', 'Car Side'), ('cmspage/icons/living/champagne.svg', 'Champagne'), ('cmspage/icons/tech/cloud.svg', 'Cloud'), ('cmspage/icons/tech/computer.svg', 'Computer'), ('cmspage/icons/sport/cricket.svg', 'Cricket'), ('cmspage/icons/people/cry.svg', 'Cry'), ('cmspage/icons/living/desk.svg', 'Desk'), ('cmspage/icons/tech/document.svg', 'Document'), ('cmspage/icons/living/donation.svg', 'Donation'), ('cmspage/icons/tech/external.svg', 'External'), ('cmspage/icons/people/father.svg', 'Father'), ('cmspage/icons/sport/football.svg', 'Football'), ('cmspage/icons/living/giving.svg', 'Giving'), ('cmspage/icons/tech/graph-flowchart.svg', 'Graph Flowchart'), ('cmspage/icons/tech/graph-trend.svg', 'Graph Trend'), ('cmspage/icons/symbols/heart.svg', 'Heart'), ('cmspage/icons/symbols/help.svg', 'Help'), ('cmspage/icons/symbols/home.svg', 'Home'), ('cmspage/icons/symbols/home-dark.svg', 'Home Dark'), ('cmspage/icons/symbols/information.svg', 'Information'), ('cmspage/icons/tech/keyboard.svg', 'Keyboard'), ('cmspage/icons/tech/laptop.svg', 'Laptop'), ('cmspage/icons/symbols/link.svg', 'Link'), ('cmspage/icons/tech/mainframe.svg', 'Mainframe'), ('cmspage/icons/living/map.svg', 'Map'), ('cmspage/icons/living/map-pin.svg', 'Map Pin'), ('cmspage/icons/tech/microphone.svg', 'Microphone'), ('cmspage/icons/tech/mobile.svg', 'Mobile'), ('cmspage/icons/living/moon.svg', 'Moon'), ('cmspage/icons/people/mother.svg', 'Mother'), ('cmspage/icons/tech/mouse.svg', 'Mouse'), ('cmspage/icons/living/news.svg', 'News'), ('cmspage/icons/tech/page.svg', 'Page'), ('cmspage/icons/tech/phone.svg', 'Phone'), ('cmspage/icons/tech/phone-call.svg', 'Phone Call'), ('cmspage/icons/symbols/point-left.svg', 'Point Left'), ('cmspage/icons/symbols/point-right.svg', 'Point Right'), ('cmspage/icons/symbols/point-up.svg', 'Point Up'), ('cmspage/icons/people/pram.svg', 'Pram'), ('cmspage/icons/living/rain.svg', 'Rain'), ('cmspage/icons/sport/referee.svg', 'Referee'), ('cmspage/icons/symbols/rss.svg', 'Rss'), ('cmspage/icons/living/run.svg', 'Run'), ('cmspage/icons/living/ship.svg', 'Ship'), ('cmspage/icons/living/sleep.svg', 'Sleep'), ('cmspage/icons/people/smile.svg', 'Smile'), ('cmspage/icons/tech/speaker.svg', 'Speaker'), ('cmspage/icons/people/speech.svg', 'Speech'), ('cmspage/icons/living/stand.svg', 'Stand'), ('cmspage/icons/living/star.svg', 'Star'), ('cmspage/icons/living/sun.svg', 'Sun'), ('cmspage/icons/sport/tennis.svg', 'Tennis'), ('cmspage/icons/train.svg', 'Train'), ('cmspage/icons/living/trash.svg', 'Trash'), ('cmspage/icons/truck.svg', 'Truck'), ('cmspage/icons/walk.svg', 'Walk'), ('cmspage/icons/symbols/warning.svg', 'Warning'), ('cmspage/icons/living/water.svg', 'Water'), ('cmspage/icons/living/water-tap.svg', 'Water Tap'), ('cmspage/icons/living/wheelchair.svg', 'Wheelchair')], default='', help_text='Select an icon to display next to the link', max_length=64, verbose_name='Icon')),
                ('menu_icon_color', models.CharField(blank=True, choices=[('text-body', 'Normal'), ('text-white', 'White'), ('text-black', 'Dark'), ('text-primary', 'Primary'), ('text-secondary', 'Secondary'), ('text-success', 'Success'), ('text-warning', 'Warning'), ('text-info', 'Info'), ('text-danger', 'Danger'), ('text-light', 'Light'), ('text-dark', 'Dark'), ('text-muted', 'Muted'), ('text-black-50', 'Black 50% opacity'), ('text-white-50', 'White 50% opacity')], default='text-body', help_text='Specify a theme color for the icon', max_length=16, verbose_name='Icon Color')),
                ('link_document', models.ForeignKey(blank=True, help_text="Select a document to link (leave blank for internal page or custom URL).Leave title blank to use this document's title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Select Document')),
                ('link_page', models.ForeignKey(blank=True, help_text="Select an internal page to link (leave blank for custom URL or document).Leave title blank to use this page's title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_links', to='wagtailcore.page', verbose_name='Select Page')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent link to add it to a sub-menu, or blank for a top-level menu item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmspage.menulink')),
                ('site', models.ForeignKey(default=1, help_text='Select the site to which the menu link applies', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Menu Link',
                'ordering': ['menu_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmspage_tags', to='wagtailcore.page')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cmspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Tags used to search for this page (optional)', through='cmspage.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='CMSHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_title', models.BooleanField(default=True, help_text='Display the page title on the page')),
                ('display_tags', models.BooleanField(default=False, help_text='Display the page tags on the page')),
                ('seo_keywords', models.CharField(blank=True, help_text='SEO Keywords', max_length=255)),
                ('body', wagtail.fields.StreamField([('hero', 4), ('title', 6), ('cards', 17), ('image_and_text', 25), ('cta', 28), ('richtext', 31), ('video', 33), ('large_image', 34), ('table', 35), ('carousel', 36), ('new_section', 37)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bg-transparent', 'Transparent'), ('bg-body', 'Page'), ('bg-light', 'Light'), ('bg-dark', 'Dark'), ('bg-white', 'White'), ('bg-black', 'Dark'), ('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-success', 'Success'), ('bg-warning', 'Warning'), ('bg-info', 'Info'), ('bg-danger', 'Danger')], 'help_text': 'Background type or color'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bg-opacity-100', '100%'), ('bg-opacity-75', '75%'), ('bg-opacity-50', '50%'), ('bg-opacity-25', '25%'), ('bg-gradient', 'Gradient')], 'help_text': 'Background opacity'}), 2: ('wagtail.blocks.StructBlock', [[('background', 0), ('opacity', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('bg', 2), ('image', 3)]], {'label': 'Hero Image', 'max_num': 1}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title text to display', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('bg', 2), ('text', 5)]], {'label': 'Title', 'max_num': 1}), 7: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Bold title text for this card (len=255)', 'label': 'Card Title', 'max_length': 255, 'null': True, 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'help_text': 'Optional text for this card', 'label': 'Card Text', 'null': True, 'required': False}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image (resized)', 'label': 'Card Image', 'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page link', 'required': False}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document link', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Extra link', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Button Title (use hyphen for special link button)', 'max_length': 255, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page_link', 10), ('doc_link', 11), ('extra_link', 12), ('button_title', 13)]], {'help_text': 'Enter a page or document, or an external link', 'label': 'Card Link', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('image', 9), ('link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('bg', 2), ('cards', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'null': True}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width centered'), ('left', 'Image to the left'), ('right', 'Image to the right')], 'help_text': 'Full image - text below, Image left - text right, or image right - text left.'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('standard', 'Standard 786x552'), ('landscape', 'Landscape 786x1104'), ('portrait', 'Portrait 786x300')], 'help_text': 'Layout - match with picture dimensions'}), 21: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Max length of 60 characters.', 'max_length': 60, 'null': True, 'required': False}), 22: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'usefont'], 'help_text': 'Description for this item', 'required': False}), 23: ('wagtail.blocks.BooleanBlock', (), {'blank': True, 'default': False, 'help_text': 'Overlay text on image', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('page_link', 10), ('doc_link', 11), ('extra_link', 12), ('button_title', 13)]], {'blank': True, 'null': True, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('bg', 2), ('image', 18), ('image_alignment', 19), ('image_size', 20), ('title', 21), ('text', 22), ('overlay', 23), ('link', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Max length of 60 characters, optional', 'max_length': 60, 'null': True, 'required': False}), 27: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'usefont'], 'help_text': 'Call to action text, optional (max=200)', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('bg', 2), ('title', 26), ('text', 27), ('link', 24)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Display title, optional (max len=120)', 'max_length': 120, 'null': True, 'required': False}), 30: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'usefont'], 'help_text': 'Rich text block, required'}), 31: ('wagtail.blocks.StructBlock', [[('bg', 2), ('title', 29), ('content', 30)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 33: ('wagtail.blocks.StructBlock', [[('bg', 2), ('title', 26), ('video', 32), ('text', 27)]], {}), 34: ('wagtail.blocks.StructBlock', [[('bg', 2), ('image', 3)]], {}), 35: ('cmspage.blocks.CustomTableBlock', (), {}), 36: ('wagtail.blocks.StructBlock', [[('bg', 2)]], {}), 37: ('cmspage.blocks.NewSectionBlock', (), {})}, null=True)),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Tags used to search for this page (optional)', through='cmspage.PageTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'CMS Home Page',
                'verbose_name_plural': 'CMS Home Pages',
            },
            bases=('wagtailcore.page', cmspage.mixins.CMSTemplateMixin),
        ),
        migrations.CreateModel(
            name='SiteVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vars', models.JSONField(blank=True, default=dict, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Variables',
            },
        ),
    ]
