# Generated by Django 5.1.1 on 2024-09-08 02:36

import cmspage.mixins
import cmspage.models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        ("wagtailcore", "0052_pagelogentry"),
        ("wagtaildocs", "0007_merge"),
        ("wagtailimages", "0010_change_on_delete_behaviour"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("display_title", models.BooleanField(default=True, help_text="Display the page title on the page")),
                ("display_tags", models.BooleanField(default=False, help_text="Display the page tags on the page")),
                ("seo_keywords", models.CharField(blank=True, help_text="SEO Keywords", max_length=255)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 0),
                            ("title", 2),
                            ("cards", 13),
                            ("image_and_text", 20),
                            ("cta", 23),
                            ("richtext", 26),
                            ("video", 28),
                            ("large_image", 29),
                            ("table", 30),
                            ("carousel", 31),
                            ("new_section", 32),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("cmspage.blocks.HeroImageBlock", (), {"label": "Hero Image", "max_num": 1}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title text to display", "required": True},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("text", 1)]], {"label": "Title", "max_num": 1}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Bold title text for this card (len=255)",
                                    "max_length": 255,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Optional text for this card",
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Image - auto-cropped 570x370px", "required": False},
                            ),
                            6: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page link", "required": False}),
                            7: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document link", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Extra link", "max_length": 255, "required": False},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": False},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("page_link", 6), ("doc_link", 7), ("extra_link", 8), ("button_title", 9)]],
                                {"help_text": "Enter a link or select a page/document", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 3), ("text", 4), ("image", 5), ("link", 10)]],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                            13: ("wagtail.blocks.StructBlock", [[("cards", 12)]], {}),
                            14: ("wagtail.images.blocks.ImageChooserBlock", (), {"blank": True, "null": True}),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full", "Full width centered"),
                                        ("left", "Image to the left"),
                                        ("right", "Image to the right"),
                                    ],
                                    "help_text": "Full image - text below, Image left - text right, or image right - text left.",
                                },
                            ),
                            16: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("standard", "Standard 786x552"),
                                        ("landscape", "Landscape 786x1104"),
                                        ("portrait", "Portrait 786x300"),
                                    ],
                                    "help_text": "Layout - match with picture dimensions",
                                },
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Max length of 60 characters.",
                                    "max_length": 60,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "blank": True,
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "code",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Description for this item",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("page_link", 6), ("doc_link", 7), ("extra_link", 8), ("button_title", 9)]],
                                {"blank": True, "null": True, "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 14),
                                        ("image_alignment", 15),
                                        ("image_size", 16),
                                        ("title", 17),
                                        ("text", 18),
                                        ("link", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Max length of 60 characters, optional",
                                    "max_length": 60,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "blank": True,
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "code",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Call to action text, optional (max=200)",
                                    "required": False,
                                },
                            ),
                            23: ("wagtail.blocks.StructBlock", [[("title", 21), ("text", 22), ("link", 19)]], {}),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Display title, optional (max len=120)",
                                    "max_length": 120,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "code",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Rich text block, required",
                                },
                            ),
                            26: ("wagtail.blocks.StructBlock", [[("title", 24), ("content", 25)]], {}),
                            27: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            28: ("wagtail.blocks.StructBlock", [[("title", 21), ("video", 27), ("text", 22)]], {}),
                            29: ("cmspage.blocks.LargeImageBlock", (), {}),
                            30: ("cmspage.blocks.CustomTableBlock", (), {}),
                            31: ("wagtail.blocks.StructBlock", [[]], {}),
                            32: ("cmspage.blocks.NewSectionBlock", (), {}),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
            },
            bases=("wagtailcore.page", cmspage.mixins.CMSTemplateMixin),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("taggit.tag",),
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "carousel_title",
                    models.CharField(
                        blank=True, help_text="Display title, optional (max len=120)", max_length=120, null=True
                    ),
                ),
                ("carousel_content", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "carousel_attribution",
                    models.CharField(
                        blank=True, help_text="Display title, optional (max len=120)", max_length=120, null=True
                    ),
                ),
                (
                    "carousel_interval",
                    models.IntegerField(default=12000, help_text="Keep visible for time in milliseconds"),
                ),
                (
                    "carousel_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "parent_pg",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_images",
                        to="cmspage.cmspage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "menu_order",
                    models.IntegerField(default=0, help_text="Specify the order in the menu", verbose_name="Order"),
                ),
                (
                    "menu_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the menu title",
                        max_length=32,
                        null=True,
                        validators=[cmspage.models.min_length_validator],
                        verbose_name="Menu Title",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Set a custom URL if not linking to a page or document",
                        verbose_name="External Link",
                    ),
                ),
                (
                    "link_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a document to link (leave blank for internal page or custom URL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Select Document",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select an internal page to link (leave blank for custom URL or document)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Select Page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a parent link to add it to a sub-menu, or blank for a top-level menu item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cmspage.menulink",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        help_text="Select the site to which the menu link applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Link",
                "ordering": ["menu_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cmspage_tags", to="wagtailcore.page"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cmspage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Tags used to search for this page (optional)",
                through="cmspage.PageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="CMSHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("display_title", models.BooleanField(default=True, help_text="Display the page title on the page")),
                ("display_tags", models.BooleanField(default=False, help_text="Display the page tags on the page")),
                ("seo_keywords", models.CharField(blank=True, help_text="SEO Keywords", max_length=255)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 0),
                            ("title", 2),
                            ("cards", 13),
                            ("image_and_text", 20),
                            ("cta", 23),
                            ("richtext", 26),
                            ("video", 28),
                            ("large_image", 29),
                            ("table", 30),
                            ("carousel", 31),
                            ("new_section", 32),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("cmspage.blocks.HeroImageBlock", (), {"label": "Hero Image", "max_num": 1}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title text to display", "required": True},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("text", 1)]], {"label": "Title", "max_num": 1}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Bold title text for this card (len=255)",
                                    "max_length": 255,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Optional text for this card",
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Image - auto-cropped 570x370px", "required": False},
                            ),
                            6: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page link", "required": False}),
                            7: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document link", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Extra link", "max_length": 255, "required": False},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": False},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("page_link", 6), ("doc_link", 7), ("extra_link", 8), ("button_title", 9)]],
                                {"help_text": "Enter a link or select a page/document", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 3), ("text", 4), ("image", 5), ("link", 10)]],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                            13: ("wagtail.blocks.StructBlock", [[("cards", 12)]], {}),
                            14: ("wagtail.images.blocks.ImageChooserBlock", (), {"blank": True, "null": True}),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full", "Full width centered"),
                                        ("left", "Image to the left"),
                                        ("right", "Image to the right"),
                                    ],
                                    "help_text": "Full image - text below, Image left - text right, or image right - text left.",
                                },
                            ),
                            16: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("standard", "Standard 786x552"),
                                        ("landscape", "Landscape 786x1104"),
                                        ("portrait", "Portrait 786x300"),
                                    ],
                                    "help_text": "Layout - match with picture dimensions",
                                },
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Max length of 60 characters.",
                                    "max_length": 60,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "blank": True,
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "code",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Description for this item",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("page_link", 6), ("doc_link", 7), ("extra_link", 8), ("button_title", 9)]],
                                {"blank": True, "null": True, "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 14),
                                        ("image_alignment", 15),
                                        ("image_size", 16),
                                        ("title", 17),
                                        ("text", 18),
                                        ("link", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Max length of 60 characters, optional",
                                    "max_length": 60,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "blank": True,
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "code",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Call to action text, optional (max=200)",
                                    "required": False,
                                },
                            ),
                            23: ("wagtail.blocks.StructBlock", [[("title", 21), ("text", 22), ("link", 19)]], {}),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Display title, optional (max len=120)",
                                    "max_length": 120,
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "code",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Rich text block, required",
                                },
                            ),
                            26: ("wagtail.blocks.StructBlock", [[("title", 24), ("content", 25)]], {}),
                            27: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            28: ("wagtail.blocks.StructBlock", [[("title", 21), ("video", 27), ("text", 22)]], {}),
                            29: ("cmspage.blocks.LargeImageBlock", (), {}),
                            30: ("cmspage.blocks.CustomTableBlock", (), {}),
                            31: ("wagtail.blocks.StructBlock", [[]], {}),
                            32: ("cmspage.blocks.NewSectionBlock", (), {}),
                        },
                        null=True,
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="Tags used to search for this page (optional)",
                        through="cmspage.PageTag",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Home Page",
                "verbose_name_plural": "CMS Home Pages",
            },
            bases=("wagtailcore.page", cmspage.mixins.CMSTemplateMixin),
        ),
        migrations.CreateModel(
            name="SiteVariables",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vars", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variables", to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Variables",
            },
        ),
    ]
