# Generated by Django 4.2.3 on 2023-07-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmshomepage',
            options={'verbose_name': 'CMS Home Page', 'verbose_name_plural': 'CMS Home Pages'},
        ),
    ]
