# Generated by Django 5.1.1 on 2024-09-17 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='link_document',
            field=models.ForeignKey(blank=True, help_text="Select a document to link (leave blank for internal page or custom URL).Leave title blank to use this document's title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Select Document'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text="Select an internal page to link (leave blank for custom URL or document).Leave title blank to use this page's title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Select Page'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='link_url',
            field=models.URLField(blank=True, help_text='Set a custom URL if not linking to a page or document.Title is required for this link type', verbose_name='External Link'),
        ),
    ]
