[tool.poetry]
name = "wagtail-cmspage"
version = "2024.3.1"
description = "Base extensible CMSPage type for Wagtail"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "cmspage"}
]

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0"
wagtail = "^6.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
ruff = "^0.5.5"

[tool.poetry.group.test.dependencies]
pytest = "^7.2"
pytest-django = "^4.8.0"
pytest-mock = "^3.14.0"
pytest-cov = "^5.0.0"

[tool.pytest.ini_options]
testpaths = ["cmspage"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
