[tool.poetry]
name = "wagtail-cmspage"
version = "2024.1.0"
description = "Base extensible CMSPage type for Wagtail"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "cmspage"}
]

[tool.poetry.dependencies]
python = "^3.10"
django = ">=5.0"
wagtail = ">=6.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
ruff = "^0.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
