[tool.poetry]
name = "wagtail-cmspage"
version = "1.1.0"
description = "Base CMSPage type for Wagtail"
authors = ["David Nugent <davidn@uniquode.io>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "cmspage"}
]

[tool.poetry.dependencies]
python = ">= 3.10"
django = ">= 4.1"
wagtail = ">= 4.2, >= 5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
